#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:
# Install nginx
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start