#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
srt_for_replcmnt="server_name _;\n\trewrite ^\/redirect_me https:\/\/thierrybakera.vercel.app permanent;"
sudo sed -i "s/server_name _;/$srt_for_replcmnt/" /etc/nginx/sites-enabled/default

sudo service nginx restart