#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html
str_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/thierrybakera.vercel.app permanent;"
sudo sed -i "s/server_name _;/$str_for_replacement/" /etc/nginx/sites-enabled/default

# code to create error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
