#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Trafic will be sent to web-01 and web-02 servers
# Algorithm -> roundrobin


sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  thierry-frontend
        bind *:80
        mode http
        default_backend thierry-backend
backend thierry-backend
        balance roundrobin
        server 228809-web-01 52.91.165.160:80 check
        server 228809-web-02 35.153.98.133:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart