#!/usr/bin/env bash
# debugging nginx port 80
# Delete the existing ../sites-enabled/default and replace it with a copy of

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart